### ISSUE TITLE
Any plan for implementing Dependency relation 

### ISSUE THREAD

**Issue by arindam324** [NikitaSmithTheOne/react-gantt-chart#17]
is there any future plans for implementing dependency relations like start to finish or finish to start etc . For now  there is no dependency conflict but i think there's should be a way to turn on and off this and the default behavior should be an error if there's a dependency conflict .

**Comment by NikitaSmithTheOne** [comment]
Hi, @arindam324! For now we have [the roadmap](https://github.com/NikitaSmithTheOne/react-gantt-chart#roadmap). Unfortunately, I don't have so much time now in order to develop the library. So if you are looking for some implementation that doesn't implemented yet, you can make PR w/ all you need. It'll be really nice!

**Comment by arindam324** [comment]
> Hi, @arindam324! For now we have [the roadmap](https://github.com/NikitaSmithTheOne/react-gantt-chart#roadmap). Unfortunately, I don't have so much time now in order to develop the library. So if you are looking for some implementation that doesn't implemented yet, you can make PR w/ all you need. It'll be really nice!
i would to love to contribute  but can you help me move around in this project

**Comment by NikitaSmithTheOne** [comment]
> > Hi, @arindam324! For now we have [the roadmap](https://github.com/NikitaSmithTheOne/react-gantt-chart#roadmap). Unfortunately, I don't have so much time now in order to develop the library. So if you are looking for some implementation that doesn't implemented yet, you can make PR w/ all you need. It'll be really nice!
> > i would to love to contribute  but can you help me move around in this project

You can join [discord channel](https://discord.gg/fJ7TuVYNRg).
