### ISSUE TITLE
How can i solve usestate aray

### ISSUE THREAD

**Issue by bubblegum8** [NikitaSmithTheOne/react-gantt-chart#18]
An element access expression should take a
![image](https://user-images.githubusercontent.com/49344878/198921169-7d9a6548-a411-4e70-a3dd-1bd6772a6003.png)
n argument.

**Comment by NikitaSmithTheOne** [comment]
Hi, @bubblegum8! Can you provide full code snippet? I believe [the example](https://github.com/NikitaSmithTheOne/react-gantt-chart/blob/master/src/example/App.tsx) will help you.
