### ISSUE TITLE
How to hide this content

### ISSUE THREAD

**Issue by Sallyfafafa** [NikitaSmithTheOne/react-gantt-chart#19]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/40735740/202149530-681e527d-b0ef-48f2-97ef-98699e33baa9.png">

 I'm looking forward to your reply soon.

**Comment by NikitaSmithTheOne** [comment]
Hi, @Sallyfafafa! TaskListHeader component has `columns` prop, by default it's [`["Name", "From", "To"]`](https://github.com/NikitaSmithTheOne/react-gantt-chart/blob/cce6623caa4ea0c2c767c9ba4d2d3cc15027033d/src/lib/containers/TaskList/components/TaskListHeader.tsx#L20). So if you are going to hide the last 2 columns just delete `from` and `to` strings from the array [like so](https://github.com/NikitaSmithTheOne/react-gantt-chart/blob/cce6623caa4ea0c2c767c9ba4d2d3cc15027033d/src/lib/examples/GanttNationalResources/GanttNationalResources.tsx#L506). As you can see it's possible to rename columns as well.
