### ISSUE TITLE
Multibar row mode on the Gantt original

### ISSUE THREAD

**Issue by thegliche** [NikitaSmithTheOne/react-gantt-chart#20]
Hello @NikitaSmithTheOne , 
Kindly assist in adding the multibar row mode on the Gantt original

**Comment by NikitaSmithTheOne** [comment]
Hi, @thegliche! Till now `GanttOriginal` doesn't have such possibility. But you can implement it by yourself with ease. You just need to check [this part](https://github.com/NikitaSmithTheOne/react-gantt-chart/blob/cce6623caa4ea0c2c767c9ba4d2d3cc15027033d/src/lib/examples/GanttNationalResources/GanttNationalResources.tsx#L238) and inside of your tasks list use [`line`](https://github.com/NikitaSmithTheOne/react-gantt-chart/blob/cce6623caa4ea0c2c767c9ba4d2d3cc15027033d/src/example/helpers/index.ts#L8) property.

**Comment by thegliche** [comment]
Thanks for the quick response @NikitaSmithTheOne!, I've tried that, but it's still not working I'd say. What else could I be missing?

**Comment by NikitaSmithTheOne** [comment]
@thegliche, I've checked. So yes I was wrong... I forgot that `GanttOriginal` chart hasn't adaptation for multibar output. I believe the best you can do now is to use `GanttNationalResources` as base for your implementation with styles update.

**Comment by thegliche** [comment]
Thanks, @NikitaSmithTheOne, yeah I just added the move and resize to the GanttNationalResource component. Hope it should be good to go, should I create a PR?

**Comment by NikitaSmithTheOne** [comment]
@thegliche, make it. Let's see what's there.

**Comment by thegliche** [comment]
Can't push a PR, but realized I might have created some new issues.
